# The 'version' tag is obsolete in newer Docker Compose versions, so we can remove it.
services:
  # Django Web Application Service
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/static_cdn
    ports:
      - "8000:8000"
    # We use env_file to load the bulk of our settings like SECRET_KEY, DEBUG, etc.
    env_file:
      - .env
    # --- THIS IS THE FINAL FIX ---
    # We add an 'environment' block to EXPLICITLY set the REDIS_URL.
    # An explicitly set variable in 'environment' takes precedence over 'env_file'.
    # This guarantees the web container uses the correct address to connect to the Redis service.
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - app_network

  # Celery Worker Service
  celery_worker:
    build: .
    command: celery -A tts_project.settings.celery worker -l info
    volumes:
      - .:/app
      - media_data:/app/media
    # The celery worker correctly loads its settings from the env_file, so we leave it.
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - app_network

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app_network

# Define named volumes for persistent data storage.
volumes:
  pg_data:
  redis_data:
  media_data:
  static_data:

# Define a custom bridge network for internal communication.
networks:
  app_network:
    driver: bridge
