"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# Administrator contact information for error notifications
# Format: (name, email) tuples
ADMINS = [
    (admin_name, admin_email)
    for admin_name, admin_email in [
        tuple(pair.split(","))
        for pair in config("ADMINS", default="").split(";")
        if pair.strip() and "," in pair
    ]
] or [("Admin", config("DEFAULT_ADMIN_EMAIL", default="admin@example.com"))]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by django-allauth
    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "widget_tweaks",
    "storages",  # For django-storages (S3)
    "django_ratelimit",  # For rate limiting
    # This project apps
    "landing",
    "users.apps.UsersConfig",
    "speech_processing.apps.SpeechProcessingConfig",
    "document_processing",
    "crispy_forms",
    "crispy_bootstrap5",
    # 'accounts',
    # 'audio_playback',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Project-level templates (e.g., base.html)
        "APP_DIRS": True,  # Look for templates in app-specific template directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ==================== APPLICATION CONSTANTS ====================
# These constants are used throughout the application for configuration
# and should be centralized here for easy maintenance.

# File upload and processing
UPLOAD_MAX_FILENAME_LENGTH = (
    200  # Max filename length after sanitization (most filesystems support 255)
)
UPLOAD_MAX_FILE_SIZE_MB = 100  # Max file upload size in MB
DOCUMENT_TITLE_MAX_LENGTH = 255  # Max length for document titles
RATE_LIMIT_UPLOADS_PER_HOUR = 10  # Maximum document uploads per hour per user

# Content processing
MARKDOWN_MAX_LENGTH = 1_000_000  # 1MB max per page for markdown content
MIN_CONTENT_LENGTH = 100  # Minimum characters for processed document content

# Audio generation and processing
POLLY_MAX_CHARS_PER_REQUEST = 3000  # AWS Polly character limit per request
POLLY_AUDIO_CACHE_SECONDS = 31_536_000  # Cache audio for 1 year (365 days)

# Audio presigned/signed URL expiration (in seconds)
AUDIO_PRESIGNED_URL_EXPIRATION_SECONDS = 3600  # 1 hour
AUDIO_DOWNLOAD_EXPIRATION_SECONDS = 3600  # 1 hour

# CloudFront signed URL expiration (in seconds)
CLOUDFRONT_EXPIRATION = 3600  # 1 hour

# Dashboard and analytics
DASHBOARD_MAX_DAYS_LOOKBACK = 365  # Maximum days for analytics queries (1 year)
DASHBOARD_DEFAULT_DAYS = 30  # Default days for analytics queries
DASHBOARD_PAGE_SIZE = 50  # Default items per page in dashboard
DASHBOARD_MIN_PAGE_SIZE = 10  # Minimum items per page

# Time constants (in seconds)
ONE_HOUR_SECONDS = 3600
ONE_DAY_SECONDS = 86400
ONE_YEAR_SECONDS = 31_536_000

# Password reset
PASSWORD_RESET_TIMEOUT_SECONDS = 259200  # 3 days (default for production)

# Cache and timeout settings
DEFAULT_CACHE_TIMEOUT_SECONDS = 3600  # 1 hour
DATABASE_POOL_MAX_CONNECTIONS = 50  # Max database connections in pool
SOCKET_TIMEOUT_SECONDS = 5  # Socket timeout for network operations

# Error tracking
MAX_ERROR_MESSAGE_LENGTH = 500  # Max length for error messages in logs

# ==================== HTTP STATUS CODE CONSTANTS ====================
# Standard HTTP status codes used throughout the application
HTTP_200_OK = 200
HTTP_400_BAD_REQUEST = 400
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_405_METHOD_NOT_ALLOWED = 405
HTTP_409_CONFLICT = 409
HTTP_429_TOO_MANY_REQUESTS = 429
HTTP_500_INTERNAL_SERVER_ERROR = 500

# ==================== ERROR MESSAGE CONSTANTS ====================
# Common error messages used across the application
ERROR_VOICE_ID_REQUIRED = "Voice ID is required"
ERROR_INVALID_JSON_DATA = "Invalid JSON data"
ERROR_PERMISSION_DENIED = "Permission denied"
ERROR_DOCUMENT_NOT_FOUND = "Document not found"
ERROR_AUDIO_NOT_FOUND = "Audio not found"
ERROR_INVALID_REQUEST_METHOD = "Invalid request method"
ERROR_ONLY_FAILED_DOCUMENTS_CAN_BE_RETRIED = "Only failed documents can be retried"
ERROR_ONLY_FAILED_AUDIO_CAN_BE_RETRIED = "Only failed audio files can be retried"
ERROR_RATE_LIMIT_EXCEEDED_AUDIO_RETRY = "You have exceeded the maximum number of retries allowed (10 per hour). Please try again later."
ERROR_RATE_LIMIT_EXCEEDED_DOCUMENT_RETRY = "You have exceeded the maximum number of retries allowed (5 per hour). Please try again later."
ERROR_AN_ERROR_OCCURRED_AUDIO_GENERATION = "An error occurred during audio generation"
ERROR_AN_ERROR_OCCURRED_DOCUMENT_RETRY = "An error occurred while retrying the document"
ERROR_AN_ERROR_OCCURRED_AUDIO_RETRY = "An error occurred while retrying the audio"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


SESSION_ENGINE = "django.contrib.sessions.backends.db"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ==================== ENVIRONMENT CONFIGURATION ====================
# Determines which environment-specific settings to use
# Set via environment variable: ENVIRONMENT=production or development
ENVIRONMENT = config("ENVIRONMENT", default="development")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = f"https://{config('STATIC_CLOUDFRONT_DOMAIN')}/staticfiles/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "document_processing.storage_backends.StaticStorage",
    },
    "default": {
        "BACKEND": "document_processing.storage_backends.MediaStorage",
    },
}

# # Media files (user uploads)
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django Allauth settings
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
SOCIALACCOUNT_QUERY_EMAIL = ACCOUNT_EMAIL_REQUIRED
SOCIALACCOUNT_AUTO_SIGNUP = True


# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": config("GOOGLE_CLIENT_ID", default=""),
            "secret": config("GOOGLE_SECRET", default=""),
            "key": "",
        }
    },
    "github": {
        "APP": {
            "client_id": config("GITHUB_CLIENT_ID", default=""),
            "secret": config("GITHUB_SECRET", default=""),
            "key": "",
        },
        "VERIFIED_EMAIL": True,
    },
}


# Celery Settings
CELERY_BROKER_URL = config("REDIS_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config("REDIS_URL", default="redis://redis:6379/0")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Accra"
CELERY_TASK_TRACK_STARTED = True

# ==================== CELERY TIMEOUT SETTINGS ====================
# These settings prevent tasks from hanging indefinitely.
#
# SOFT TIMEOUT: 25 minutes
#   - A signal is sent to the task to gracefully shut down
#   - Task can clean up resources and log the timeout
#   - SoftTimeLimitExceeded exception is raised
#
# HARD TIMEOUT: 30 minutes
#   - If task still running after soft timeout, it's forcefully killed
#   - No graceful cleanup possible
#   - Should never be reached if soft timeout handler works
#
# Best practice: hard_timeout > soft_timeout > typical_task_time
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes - allows graceful shutdown
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes - hard kill

# ==================== CELERY RETRY SETTINGS ====================
# These settings determine how tasks behave when they fail.
#
# max_retries: Don't retry indefinitely (prevents infinite loops)
# default_retry_delay: Wait between retries (gives system time to recover)
# retry_backoff: exponential backoff (prevents thundering herd)
CELERY_TASK_MAX_RETRIES = 3
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute between retries
CELERY_TASK_AUTORETRY_FOR = (Exception,)  # Auto-retry on any exception
CELERY_TASK_RETRY_BACKOFF = True  # Use exponential backoff
CELERY_TASK_RETRY_BACKOFF_MAX = 600  # Max 10 minutes between retries
CELERY_TASK_RETRY_JIT = True  # Add jitter to prevent thundering herd


# ==================== RATE LIMITING SETTINGS ====================
# These settings control django-ratelimit behavior for protecting against DoS attacks
#
# Cache backend for storing rate limit counters
# Uses Redis to track request counts across requests
# Falls back to local memory if Redis is unavailable
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL", default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": DATABASE_POOL_MAX_CONNECTIONS,
                "retry_on_timeout": True,
            },
        },
        "TIMEOUT": DEFAULT_CACHE_TIMEOUT_SECONDS,
    },
    "ratelimit": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL", default="redis://127.0.0.1:6379/2"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": SOCKET_TIMEOUT_SECONDS,
            "SOCKET_TIMEOUT": SOCKET_TIMEOUT_SECONDS,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "IGNORE_EXCEPTIONS": True,
        },
        "TIMEOUT": DEFAULT_CACHE_TIMEOUT_SECONDS,
    },
}

# Rate limit cache to use (dedicated Redis database for rate limits)
RATELIMIT_CACHE = "ratelimit"

# Rate limit settings for different endpoints
# key format: app:endpoint:rate
# Example: user uploads limited to 10 per hour
RATELIMIT_CONFIG = {
    "document:upload": f"{RATE_LIMIT_UPLOADS_PER_HOUR}/h",  # uploads per hour per user
}

# Rate limits for retry operations
AUDIO_RETRY_RATE_LIMIT = "10/h"  # Maximum audio retries per hour per user
DOCUMENT_RETRY_RATE_LIMIT = "5/h"  # Maximum document retries per hour per user


# AWS S3 / Polly Settings (using django-storages and boto3)
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = config("AWS_DEFAULT_REGION")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False

DEFAULT_FILE_STORAGE = "document_processing.storage_backends.MediaStorage"

AWS_HEADERS = {
    "Cache-Control": "public, max-age=2419200",  # Cache for 4 weeks (2,419,200 seconds)
}


AUTH_USER_MODEL = "users.CustomUser"

CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

LOGGING = {
    "version": 1,
    # This setting is crucial. It ensures that loggers defined by Django
    # or other third-party apps are not disabled.
    "disable_existing_loggers": False,
    # Filters to sanitize sensitive data
    "filters": {
        "sensitive_data": {
            "()": "core.security_utils.SensitiveDataFilter",
        },
    },
    # Formatters define the layout of your log messages.
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
        },
        "simple": {
            "format": "[%(levelname)s] %(message)s",
        },
    },
    # Handlers decide what to do with a log message (e.g., print to console, write to file).
    "handlers": {
        "console": {
            "level": "DEBUG",  # Capture all messages from DEBUG level and up.
            "class": "logging.StreamHandler",  # Prints to standard output/error.
            "formatter": "simple",
            "filters": ["sensitive_data"],  # Apply sensitive data filter
        },
    },
    # Loggers are the entry point into the logging system.
    "loggers": {
        # This is the "root" logger. It catches messages from all loggers
        # that don't have a more specific configuration.
        "django": {
            "handlers": ["console"],
            "level": "INFO",  # For Django's own logs, INFO is usually enough.
            "propagate": True,
        },
        # This will catch logs from `document_processing` app.
        "document_processing": {
            "handlers": ["console"],
            "level": "DEBUG",  # Show all debug messages from your app.
            "propagate": True,
        },
        # This will catch logs from `speech_processing` app.
        "speech_processing": {
            "handlers": ["console"],
            "level": "DEBUG",  # Show all debug messages from your app.
            "propagate": True,
        },
        # This will catch logs from the `core` app.
        "core": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        # You can add other apps here as your project grows.
    },
}
