"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# Administrator contact information for error notifications
# Format: (name, email) tuples
ADMINS = [
    (admin_name, admin_email)
    for admin_name, admin_email in [
        tuple(pair.split(","))
        for pair in config("ADMINS", default="").split(";")
        if pair.strip() and "," in pair
    ]
] or [("Admin", config("DEFAULT_ADMIN_EMAIL", default="admin@example.com"))]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by django-allauth
    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "widget_tweaks",
    "storages",  # For django-storages (S3)
    "django_ratelimit",  # For rate limiting
    # This project apps
    "landing",
    "users.apps.UsersConfig",
    "speech_processing.apps.SpeechProcessingConfig",
    "document_processing",
    "crispy_forms",
    "crispy_bootstrap5",
    # 'accounts',
    # 'audio_playback',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Project-level templates (e.g., base.html)
        "APP_DIRS": True,  # Look for templates in app-specific template directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


SESSION_ENGINE = "django.contrib.sessions.backends.db"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static_cdn/"


# # Media files (user uploads)
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django Allauth settings
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
SOCIALACCOUNT_QUERY_EMAIL = ACCOUNT_EMAIL_REQUIRED
SOCIALACCOUNT_AUTO_SIGNUP = True


# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": config("GOOGLE_CLIENT_ID", default=""),
            "secret": config("GOOGLE_SECRET", default=""),
            "key": "",
        }
    },
    "github": {
        "APP": {
            "client_id": config("GITHUB_CLIENT_ID", default=""),
            "secret": config("GITHUB_SECRET", default=""),
            "key": "",
        },
        "VERIFIED_EMAIL": True,
    },
}


# Celery Settings
CELERY_BROKER_URL = config("REDIS_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config("REDIS_URL", default="redis://redis:6379/0")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Accra"
CELERY_TASK_TRACK_STARTED = True

# ==================== CELERY TIMEOUT SETTINGS ====================
# These settings prevent tasks from hanging indefinitely.
#
# SOFT TIMEOUT: 25 minutes
#   - A signal is sent to the task to gracefully shut down
#   - Task can clean up resources and log the timeout
#   - SoftTimeLimitExceeded exception is raised
#
# HARD TIMEOUT: 30 minutes
#   - If task still running after soft timeout, it's forcefully killed
#   - No graceful cleanup possible
#   - Should never be reached if soft timeout handler works
#
# Best practice: hard_timeout > soft_timeout > typical_task_time
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes - allows graceful shutdown
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes - hard kill

# ==================== CELERY RETRY SETTINGS ====================
# These settings determine how tasks behave when they fail.
#
# max_retries: Don't retry indefinitely (prevents infinite loops)
# default_retry_delay: Wait between retries (gives system time to recover)
# retry_backoff: exponential backoff (prevents thundering herd)
CELERY_TASK_MAX_RETRIES = 3
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute between retries
CELERY_TASK_AUTORETRY_FOR = (Exception,)  # Auto-retry on any exception
CELERY_TASK_RETRY_BACKOFF = True  # Use exponential backoff
CELERY_TASK_RETRY_BACKOFF_MAX = 600  # Max 10 minutes between retries
CELERY_TASK_RETRY_JIT = True  # Add jitter to prevent thundering herd


# ==================== RATE LIMITING SETTINGS ====================
# These settings control django-ratelimit behavior for protecting against DoS attacks
#
# Cache backend for storing rate limit counters
# Uses Redis to track request counts across requests
# Falls back to local memory if Redis is unavailable
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL", default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True,
            },
        },
        "TIMEOUT": 3600,  # Default cache timeout: 1 hour
    },
    "ratelimit": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL", default="redis://127.0.0.1:6379/2"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "IGNORE_EXCEPTIONS": True,
        },
        "TIMEOUT": 3600,
    },
}

# Rate limit cache to use (dedicated Redis database for rate limits)
RATELIMIT_CACHE = "ratelimit"

# Rate limit settings for different endpoints
# key format: app:endpoint:rate
# Example: user uploads limited to 10 per hour
RATELIMIT_CONFIG = {
    "document:upload": "10/h",  # 10 uploads per hour per user
}


# AWS S3 / Polly Settings (using django-storages and boto3)
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = config("AWS_DEFAULT_REGION")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False

DEFAULT_FILE_STORAGE = "document_processing.storage_backends.MediaStorage"

AWS_HEADERS = {
    "Cache-Control": "public, max-age=2419200",  # Cache for 4 weeks (2,419,200 seconds)
}


AUTH_USER_MODEL = "users.CustomUser"

CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

LOGGING = {
    "version": 1,
    # This setting is crucial. It ensures that loggers defined by Django
    # or other third-party apps are not disabled.
    "disable_existing_loggers": False,
    # Filters to sanitize sensitive data
    "filters": {
        "sensitive_data": {
            "()": "core.security_utils.SensitiveDataFilter",
        },
    },
    # Formatters define the layout of your log messages.
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
        },
        "simple": {
            "format": "[%(levelname)s] %(message)s",
        },
    },
    # Handlers decide what to do with a log message (e.g., print to console, write to file).
    "handlers": {
        "console": {
            "level": "DEBUG",  # Capture all messages from DEBUG level and up.
            "class": "logging.StreamHandler",  # Prints to standard output/error.
            "formatter": "simple",
            "filters": ["sensitive_data"],  # Apply sensitive data filter
        },
    },
    # Loggers are the entry point into the logging system.
    "loggers": {
        # This is the "root" logger. It catches messages from all loggers
        # that don't have a more specific configuration.
        "django": {
            "handlers": ["console"],
            "level": "INFO",  # For Django's own logs, INFO is usually enough.
            "propagate": True,
        },
        # This will catch logs from `document_processing` app.
        "document_processing": {
            "handlers": ["console"],
            "level": "DEBUG",  # Show all debug messages from your app.
            "propagate": True,
        },
        # This will catch logs from `speech_processing` app.
        "speech_processing": {
            "handlers": ["console"],
            "level": "DEBUG",  # Show all debug messages from your app.
            "propagate": True,
        },
        # You can add other apps here as your project grows.
    },
}
